# One hot encoding
this technique need to understand, for learn next all technique. This is very basic next feature extraction technique which much have to learn. and we should follow all this technique.

# Bag of Words (BOW) 
this technique is another basic text representation technique, let's learn. 

this is very effective in ```text classification```

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({
        'text':['Bangladesh is among the most densely',
            'People\'s Republic of Bangladesh',
            'Bangladesh forms the sovereign part of the historic',
            'The country has a Bengali Muslim majority'],
        'output': [1, 0, 1, 1]
    }
)

In [3]:
df

text  output
0               Bangladesh is among the most densely       1
1                    People's Republic of Bangladesh       0
2  Bangladesh forms the sovereign part of the his...       1
3          The country has a Bengali Muslim majority       1

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
# vocabolary
print(cv.vocabulary_)

{'bangladesh': 1, 'is': 8, 'among': 0, 'the': 17, 'most': 10, 'densely': 4, 'people': 14, 'republic': 15, 'of': 12, 'forms': 5, 'sovereign': 16, 'part': 13, 'historic': 7, 'country': 3, 'has': 6, 'bengali': 2, 'muslim': 11, 'majority': 9}


In [7]:
print(bow[0].toarray())

[[1 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1]]


In [8]:
print(bow)

  (0, 1)	1
  (0, 8)	1
  (0, 0)	1
  (0, 17)	1
  (0, 10)	1
  (0, 4)	1
  (1, 1)	1
  (1, 14)	1
  (1, 15)	1
  (1, 12)	1
  (2, 1)	1
  (2, 17)	2
  (2, 12)	1
  (2, 5)	1
  (2, 16)	1
  (2, 13)	1
  (2, 7)	1
  (3, 17)	1
  (3, 3)	1
  (3, 6)	1
  (3, 2)	1
  (3, 11)	1
  (3, 9)	1


In [9]:
for i in range(4):
    print(bow[i].toarray())

[[1 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1]]
[[0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0]]
[[0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 2]]
[[0 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1]]


In [10]:
cv.transform(["Bangladesh is the country has a Bengali Muslim majority"]).toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1]])

# N-grams

In [11]:
df

text  output
0               Bangladesh is among the most densely       1
1                    People's Republic of Bangladesh       0
2  Bangladesh forms the sovereign part of the his...       1
3          The country has a Bengali Muslim majority       1

In [18]:
cv_n_grams = CountVectorizer(ngram_range=(3, 3))

n_g = cv_n_grams.fit_transform(df['text'])

In [19]:
print(cv_n_grams.vocabulary_)

{'bangladesh is among': 2, 'is among the': 7, 'among the most': 0, 'the most densely': 14, 'people republic of': 10, 'republic of bangladesh': 11, 'bangladesh forms the': 1, 'forms the sovereign': 5, 'the sovereign part': 15, 'sovereign part of': 12, 'part of the': 9, 'of the historic': 8, 'the country has': 13, 'country has bengali': 4, 'has bengali muslim': 6, 'bengali muslim majority': 3}


In [21]:
print(n_g[0].toarray())

[[1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0]]


|**benefits**|**disadvantage**|
|------------|----------------|
|1. Able to capture semantic meaning| 1. Slow down the algorithm for n-gram/bi-gram|
|2. Intuative and easy to understand|2. out of vocabolary(OOV)|

# TF-IDF

```
TF  = Term Frequency
IDF = Inverce Documents Frequency
```
$$
TF(t, d) = \frac{(Number \;of \;occurence \;of \;term \;t \;in \;document \;d)}{(Total \;number \;of \;term \;in \;the \;document \;d)}
$$
$$
IDF(t) = log_e \frac{(Total \;number \;of \;documents \;in \;the \;corpus)}{(Number \;of \;documents \;with \;term \;t \;in \;them)}
$$